# This is a basic workflow to help you get started with Actions

name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Triggers only on push to the main branch

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .                # Set to the path where your Dockerfile exists
          push: true                # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/walk-with-me:${{ github.run_number }}


